export function getLocalizedStrings( locale, collection ) {
  // ex: getLocalizedStrings("en_CA", "colour")
  // ex: getLocalizedStrings("fr_CA", "ALL")
  // ex: getLocalizedStrings("ALL")

  // English
  const en_CA = {
    gwp: "Gatineau Wildflower Project",
    welcome: "Hello",
    //screen: "Home,Search,Results,Details,About,Contact,Links,Copyright,Query Picker".split(','),
    screen: "⌂,Search,Results,Details,About,Contact,Links,Copyright,Query Picker".split(','),
    homebutton: 'Query,About,Contact,Links,Copyright'.split(','),
    all: "CLEAR",
    colour: "white,yellow,red,purple,green,brown,orange,blue,pink".split(','),
    leaf: "simple,compound,none".split(','),
    arrangement: "alternate,basal,whorled,opposite,none".split(','),
    floweringin: 'January,February,March,April,May,June,July,August,September,October,November,December'.split(','),
    speciesname:
`Achillea millefolium,
Actaea pachypoda,
Actaea rubra,
Aegopodium podagraria,
Agalinis tenuifolia,
Ageratina altissima,
Agrimonia gryposepala,
Alliaria petiolata,
Allium tricoccum,
Ambrosia artemisiifolia,
Amphicarpaea bracteata,
Anaphalis margaritacea,
Anemone acutiloba,
Anemone americana,
Anemone canadensis,
Antennaria neglecta,
Apocynum androsaemifolium,
Aquilegia canadensis,
Aralia nudicaulis,
Aralia racemosa,
Arctium lappa,
Arisaema triphyllum,
Asarum canadense,
Asclepias incarnata,
Asclepias syriaca,
Barbarea vulgaris,
Berteroa incana,
Bidens cernua,
Bidens frondosa,
Brasenia schreberi ,
Calla palustris,
Caltha palustris,
Calystegia sepium,
Campanula aparinoides,
Campanula rapunculoides,
Campanula rotundifolia,
Capnoides sempervirens,
Cardamine diphylla,
Caulophyllum giganteum,
Chamaenerion angustifolium,
Chelone glabra,
Chenopodium album,
Chimaphila umbellata,
Cichorium intybus,
Cicuta bulbifera,
Circaea canadensis,
Cirsium arvense,
Cirsium vulgare,
Claytonia caroliniana,
Clematis virginiana,
Clinopodium acinos,
Clinopodium vulgare,
Clintonia borealis,
Coeloglossum viride,
Cornus canadensis,
Cryptotaenia canadensis,
Cypripedium acaule,
Cypripedium parviflorum,
Daucus carota,
Dianthus armeria,
Dicentra canadensis,
Dicentra cucullaria,
Diervilla lonicera,
Doellingeria umbellata,
Echinops sphaerocephalus,
Echium vulgare ,
Epifagus virginiana,
Epigaea repens,
Epilobium hirsutum,
Epipactis helleborine,
Erigeron philadelphicus,
Erigeron strigosus,
Erythronium americanum,
Eupatorium perfoliatum,
Euphorbia cyparissias,
Euphrasia nemorosa ,
Eurybia macrophylla,
Euthamia graminifolia,
Eutrochium maculatum,
Fallopia cilinodis,
Fragaria vesca,
Fragaria virginiana,
Galeopsis tetrahit,
Galium mollugo,
Galium palustre,
Galium triflorum,
Gaultheria procumbens,
Geranium robertianum,
Geum aleppicum,
Geum canadense,
Geum urbanum,
Glechoma hederacea,
Helianthus divaricatus,
Hemerocallis fulva,
Hesperis matronalis,
Hieracium aurantiacum,
Hieracium caespitosum,
Hieracium paniculatum,
Hieracium umbellatum,
Hydrophyllum canadense,
Hydrophyllum virginianum,
Hylodesmum glutinosum,
Hypericum ellipticum,
Hypericum fraseri,
Hypericum perforatum,
Impatiens capensis,
Impatiens pallida,
Inula helenium,
Iris versicolor,
Lactuca canadensis,
Laportea canadensis,
Lathyrus aphaca,
Lathyrus latifolius,
Leonurus cardiaca,
Leucanthemum vulgare,
Linaria vulgaris,
Linnaea borealis,
Lobelia cardinalis,
Lobelia inflata,
Lonicera canadensis,
Lotus corniculatus,
Lycopus uniflorus,
Lysimachia borealis,
Lysimachia ciliata,
Lysimachia terrestris,
Lysimachia thyrsiflora,
Lythrum salicaria,
Maianthemum canadense,
Maianthemum racemosum,
Malva moschata,
Malva neglecta,
Medeola virginiana,
Medicago sativa,
Melampyrum lineare,
Melilotus albus,
Melilotus officinalis,
Mentha arvensis,
Micranthes virginiensis,
Mimulus ringens,
Mitchella repens,
Mitella diphylla,
Monotropa uniflora,
Myosotis laxa,
Myosoton aquaticum,
Nuphar variegata,
Nymphaea odorata,
Oclemena acuminata,
Oclemena nemoralis,
Oenothera biennis,
Oenothera parviflora,
Oenothera pilosella,
Osmorhiza claytonii,
Oxalis corniculata,
Oxalis dillenii,
Pastinaca sativa,
Pedicularis canadensis,
Penstemon pallidus,
Persicaria pensylvanica,
Persicaria sagittata,
Phryma leptostachya,
Plantago major,
Platanthera psycodes,
Polygonatum biflorum,
Polygonatum pubescens,
Pontederia cordata,
Potentilla argentea,
Potentilla norvegica,
Potentilla recta,
Potentilla simplex,
Prunella vulgaris,
Pyrola elliptica,
Ranunculus abortivus,
Ranunculus acris,
Ranunculus recurvatus,
Ranunculus repens,
Rosa acicularis,
Rudbeckia hirta,
Rudbeckia laciniata,
Sagittaria latifolia,
Sanguinaria canadensis,
Sanicula marilandica,
Saponaria officinalis,
Scrophularia marilandica,
Scutellaria galericulata,
Securigera varia,
Silene latifolia,
Silene noctiflora,
Silene vulgaris,
Sinapis arvensis,
Sium suave,
Solanum dulcamara,
Solidago caesia,
Solidago canadensis,
Solidago flexicaulis,
Solidago rugosa,
Solidago squarrosa,
Sonchus arvensis,
Sparganium emersum,
Spiraea alba,
Spiraea tomentosa,
Spiranthes cernua,
Stachys tenuifolia,
Streptopus amplexifolius,
Streptopus lanceolatus,
Symphyotrichum boreale,
Symphyotrichum ciliolatum,
Symphyotrichum cordifolium,
Symphyotrichum lanceolatum,
Symphyotrichum lateriflorum,
Symphyotrichum novae-angliae,
Symphyotrichum puniceum,
Tanacetum vulgare,
Taraxacum officinale,
Teucrium canadense,
Thalictrum dioicum,
Thalictrum pubescens,
Tiarella cordifolia,
Tragopogon dubius,
Tragopogon pratensis,
Trifolium aureum,
Trifolium pratense,
Trifolium repens,
Trillium erectum,
Trillium grandiflorum,
Trillium undulatum,
Triosteum perfoliatum,
Tussilago farfara,
Typha angustifolia,
Typha latifolia,
Urtica dioica,
Utricularia vulgaris,
Uvularia grandiflora,
Uvularia perfoliata,
Valeriana officinalis,
Verbascum blattaria,
Verbascum thapsus,
Verbena hastata,
Veronica officinalis,
Viburnum lantanoides,
Vicia cracca,
Viola canadensis,
Viola conspersa,
Viola pubescens,
Viola renifolia,
Viola sororia`.split(',').map(item => item.trim()),
    commonname:
`Alfalfa,
American cow-wheat,
American hog peanut,
American spikenard,
Arrow-leaved smartweed,
Basil thyme,
Beechdrops,
Bitter wintercress,
Bittersweet nightshade,
Black-eyed Susan,
Bladder campion,
Bloodroot,
Blue vervain,
Bluebell of Scotland,
Blue-stemmed goldenrod,
Bluntleaf waterleaf,
Bog aster,
Bouncing-bet,
Broad-leaved arrowhead,
Broad-leaved cattail,
Broad-leaved enchanter's-nightshade,
Broad-leaved helleborine,
Bulbous water-hemlock,
Bull thistle,
Bunchberry,
Butter-and-eggs,
Calico aster,
Canada anemone,
Canada avens,
Canada fly-honeysuckle,
Canada germander,
Canada goldenrod,
Canada honewort,
Canada lettuce,
Canada lousewort,
Canada thistle,
Canada violet,
Canada wild ginger,
Canada wood nettle,
Cardinal flower,
Carolina spring beauty,
Carpenter's  figwort,
Clasping-leaved twisted-stalk,
Coltsfoot,
Common bladderwort,
Common boneset,
Common buttercup,
Common dandelion,
Common evening-primrose,
Common eyebright,
Common hemp-nettle,
Common lamb's quarters,
Common mallow,
Common marsh bedstraw,
Common milkweed,
Common motherwort,
Common mullein,
Common pipsissewa,
Common plantain,
Common ragweed,
Common self-heal,
Common speedwell,
Common St. John's-wort,
Common tansy,
Common valerian,
Common viper's bugloss,
Common water-parsnip,
Common yarrow,
Corn mustard,
Creeping bellflower,
Creeping buttercup,
Creeping wood-sorrel,
Cut-leaved coneflower,
Cypress spurge,
Dame's rocket,
Deptford pink,
Devil's beggarticks,
Downy yellow violet,
Dutchman's breeches,
Early meadow-rue,
Early saxifrage,
Eastern teaberry,
Everlasting pea,
Field mint,
Field pussytoes,
Field sow-thistle,
Fireweed,
Flat-top white aster,
Fragrant water-lily,
Fraser's St. John's-wort,
Fringed black bindweed,
Fringed yellow loosestrife,
Frog orchid,
Garden bird's-foot trefoil,
Garlic mustard,
Giant blue cohosh,
Giant chickweed,
Giant Solomon's seal,
Goutweed,
Grass-leaved goldenrod,
Great burdock,
Great globe-thistle,
Green-fruited burreed,
Ground ivy,
Hairy Solomon's seal,
Hairy sweet cicely,
Hairy willowherb,
Harlequin blue flag,
Heart-leaved aster,
Heart-leaved foamflower,
Hedge false bindweed,
Herb-Robert,
Hoary alyssum,
Hobblebush,
Hooked agrimony,
Hooked buttercup,
Horseheal,
Indian cucumber-root,
Indian pipe,
Indian tobacco,
Jack-in-the-pulpit,
Kidney-leaved buttercup,
Kidney-leaved violet,
Labrador violet,
Large false Solomon's seal,
Large tick-trefoil,
Large-flowered  bellwort,
Large-leaved aster,
Lindley's aster,
Lopseed,
Marsh bellflower,
Marsh skullcap,
Maryland sanicle,
Meadow evening-primrose,
Meadow goatsbeard,
Meadow hawkweed,
Moth mullein,
Musk mallow,
Narrow-leaved cattail,
New England aster,
Night-flowering catchfly,
Nodding beggarticks,
Nodding ladies'-tresses,
Northern bush-honeysuckle,
Northern starflower,
Northern water-horehound,
Old field cinquefoil,
Orange day-lily,
Orange hawkweed,
Oxeye daisy,
Painted trillium,
Pale beardtongue,
Pale jewelweed,
Pale St. John's-wort,
Panicled hawkweed,
Partridgeberry,
Pearly everlasting,
Pennsylvania smartweed,
Perfoliate bellwort,
Perfoliate horse-gentian,
Philadelphia fleabane,
Pickerelweed,
Pink corydalis,
Pink lady's-slipper,
Prickly rose,
Purple crown-vetch,
Purple loosestrife,
Purple-stemmed aster,
Red baneberry,
Red clover,
Red columbine,
Red trillium,
Rose twisted-stalk,
Rough cinquefoil,
Rough fleabane,
Rough-stemmed goldenrod,
Round-lobed hepatica,
Rush aster,
Sharp-lobed hepatica,
Shinleaf,
Silvery cinquefoil,
Slender yellow wood-sorrel,
Slender-leaved false foxglove,
Small forget-me-not,
Small purple fringed orchid,
Small-flowered evening-primrose,
Smooth bedstraw,
Smooth hedge-nettle,
Spotted jewelweed,
Spotted Joe Pye weed,
Spreading dogbane,
Square-stemmed monkeyflower,
Squarrose goldenrod,
Squirrel-corn,
Steeplebush,
Stinging nettle,
Sulphur cinquefoil,
Swamp milkweed,
Swamp yellow loosestrife,
Tall meadow-rue,
Three-flowered bedstraw,
Trailing arbutus,
Tufted vetch,
Tufted yellow loosestrife,
Twinflower,
Two-leaved miterwort,
Two-leaved toothwort,
Umbellate hawkweed,
Variegated pond-lily,
Virginia clematis,
Virginia waterleaf,
Watershield,
White baneberry,
White campion,
White clover,
White meadowsweet,
White panicled aster,
White snakeroot,
White sweet-clover,
White trillium,
White turtlehead,
Whorled wood aster,
Wild basil,
Wild calla,
Wild carrot,
Wild chicory,
Wild leek,
Wild lily-of-the-valley,
Wild parsnip,
Wild sarsaparilla,
Wild strawberry,
Wood avens,
Woodland strawberry,
Woodland sunflower,
Woolly blue violet,
Yellow avens,
Yellow clintonia,
Yellow clover,
Yellow goatsbeard,
Yellow lady's-slipper,
Yellow marsh marigold,
Yellow sweet-clover,
Yellow trout lily,
Yellow vetchling,
Zigzag goldenrod`.split(',').map(item => item.trim()),
    familyname:
`Adoxaceae,Alismataceae,Alliaceae,Amaranthaceae,Apiaceae,Apocynaceae,Araceae,Araliaceae,Aristolochiaceae,Asteraceae,
Balsaminaceae,Berberidaceae,Boraginaceae,Brassicaceae,
Cabombaceae,Campanulaceae,Caprifoliaceae,Caryophyllaceae,Colchiaceae,Convolvulaceae,Cornaceae,
Ericaceae,Euphorbiaceae,Fabaceae,Geraniaceae,Hemerocallidaceae,Hydrophyllaceae,Hypericaceae,
Iridaceae,Lamiaceae,Lentibulariaceae,Liliaceae,Lythraceae,Malvaceae,Melanthiaceae,Montiaceae,
Nymphaeaceae,Onagraceae,Orchidaceae,Orobanchaceae,Oxalidaceae,
Papaveraceae,Phrymaceae,Plantaginaceae,Polygonaceae,Pontederiaceae,Primulaceae,
Ranunculaceae,Rosaceae,Rubiaceae,Ruscaceae,Saxifragaceae,Scrophulariaceae,Solanaceae,
Typhaceae,Urticaceae,Verbenaceae,Violaceae`.split(',').map(item => item.trim()),
    trail: "1,1B,2,3,5,6,8,9,14,15,17,18,21,23,24,25,28,29,31,32,36,38,40,50,52,53,54,55,62,72,73".split(','),
    
    // About text
    // old
    abouttitle: "About",
    /*abouttext: [
      "What would you like to know about the Gatineau Wildflower Project?",
      "Where is the Gatineau?",
      "What is a wild flower?"
    ],*/
    // 6 Feb 2023 About text with 3 sections
    aboutprojecttitle: "The project,The project".split(','),
    aboutprojecttext: `The project was initiated in 2015 when Ottawa residents Gwynneth Evans and Tom Delsey began photographing and identifying the wildflowers they encountered on the walks in Gatineau Park. Gradually that activity took on the form of a project with the aim of documenting the diversity of wildflower species that can be found in Gatineau Park in a user- friendly form that would encourage others to explore the park and take a more focused interest in the natural environment they experience there. By 2021 they had photographed and identified more 245 different species. And the search continues.

The most recent phase of the project has been focused on the development of an app designed as a user-friendly tool for browsing and searching the entire database of photos and accompanying data that visitors to the park could use as a guide to the wildflowers they encounter on their walks. In September 2020 Gwynneth and Tom teamed up with Andrea Cocks and Ken Webb who brought to the project the technical and design expertise needed to develop a prototype of the app. Then in 2022, with the prototype completed, the team began discussions with the Friends of Gatineau Park on conducting user testing with the aim of eventually hosting the app on the Friends website. User testing of the prototype began early in 2023. The plan is to have the initial release of the app available later in the year, both on the Friends website and through the Apple and Google app stores.`,
    aboutdatabasetitle: "The database,Scope of the database".split(','),
    aboutdatabasetext: `The database currently contains more than 400 photos of wildflowers, comprising 245 different species, each with accompanying data to assist the user in identifying the species. The photos were all taken on trails in Gatineau Park during the months of April through October between 2015 and 2022.

The photos for each of the species are accompanied by a standardized set of descriptors giving the scientific and vernacular names of the species, its botanical family, an indication of whether it is native to the region, and its characteristic attributes (flower colour, leaf type, leaf arrangement, and the months in which it typically flowers).

The data accompanying the photos is fully bilingual (English and French).

The scientific and vernacular names of species and the names of botanical families all conform with the taxonomy used in the Canadensys Database of Vascular Plants of Canada (VASCAN). For the common names of species in English and French only the form of name designated as the accepted vernacular in Canadensys has been included.`,
    aboutusingtitle: "Using the app,Using the app".split(','),
    aboutusingtext: `The app has been developed as a user-friendly tool for browsing and searching the entire database of photos and species attributes. It has been designed specifically for use on a smartphone so that it can be used while walking the trails in the park, but it can also be used on a tablet, laptop, or desktop as a reference source. It is fully bilingual, with interfaces, indexes, and descriptors in both English and French.

The initial search screen displays the various filters that are available to the user: flower colour, leaf type, leaf arrangement, and the months in which it typically flowers, as well as indexes for the scientific and vernacular names of the species represented in the database and the botanical families to which they belong.

The search screen automatically defaults to select the current month and indicates the number of species in the database that typically flower in that month. Choosing the default month of flowering as the sole filter, the user will then see a complete listing of species flowering in that month, arranged in alphabetic order under the scientific name of the species. Scrolling through the listing the user can select any species in the results set to view one or more photos of that species, the scientific and vernacular names of the species, its botanical family, an indication of whether it is native to the region, and its characteristic attributes (flower colour, leaf type, leaf arrangement, and the months in which it typically flowers).

Alternatively, the user can narrow the results set further by applying one or more additional filters. For example, if the user is walking in the park in May and is trying to identify a plant that they see on the trail that has a yellow flower, they can select “yellow” from the list of flower colours as a filter to be applied in addition to the default month of flowering. After applying that filter, the results set shows just the species flowering in May with yellow flowers, again arranged in alphabetic order under the scientific name of the species.

Using the app just as a conventional reference tool, the user can search the database using the indexes for the scientific and vernacular names of the species represented in the database and the botanical families to which they belong. Each of those indexes displays the names of species or families in alphabetic order. Selecting a name in the scientific name or vernacular name index will take the user directly to a display of the photos and accompanying data for that species. By selecting a name in the botanical family index, the user will see a complete listing of species in that family that are represented in the database, arranged in alphabetic order under the scientific name of the species and showing a photo of each species.`,

    querytitle: "Flower Search",
    queryresults: "results",
    queryfiltername: 'Flower colour,Leaf type,Leaf arrangement,Flowering in,Species,Name,Family,Trail number'.split(","),
    querydone: "DONE",
    yes: "yes",
    no: "no",
    flowerdetailslabels: 'Name,Family,Native,Flower colour,Leaf type,Leaf arrangement,Flowering range,# of photos'.split(',')
  }

  //const en-CA = en_CA;

  // French
  const fr_CA = {
    gwp: "Projet de fleurs sauvages de Gatineau",
    welcome: "Bonjour",
    //screen: "Accueil,Recherche,Résultats,Détails,À propos,Contactez-nous,Liens,Copyright,Query Picker".split(','),
    screen: "⌂,Recherche,Résultats,Détails,À propos,Contactez-nous,Liens,Copyright,Query Picker".split(','),
    homebutton: "Requête,À propos,Contactez-nous,Liens,Droit d'auteur".split(','),
    all: "EFFACER",
    colour: "blanc,jaune,rouge,violet,vert,brun,orange,bleu,rose".split(","),
    leaf: "simple,composée,aucune".split(","),
    arrangement: "alternes,basales,verticillées,opposées,aucune".split(','),
    floweringin: 'janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre'.split(','),
    commonname:
`Achillée millefeuille,
Actée à gros pédicelles,
Actée rouge,
Agripaume cardiaque,
Aigremoine à sépales crochus,
Ail des bois,
Alliaire officinale,
Amphicarpe bractéolée,
Ancolie du Canada,
Anémone du Canada,
Antennaire négligée,
Apocyn à feuilles d'androsème,
Aralie à grappes,
Aralie à tige nue,
Arisème petit-prêcheur,
Asaret du Canada,
Asclépiade commune,
Asclépiade incarnate,
Aster à feuilles cordées,
Aster à fleurs latérales,
Aster à grandes feuilles,
Aster à ombelles,
Aster acuminé,
Aster boréal,
Aster ciliolé,
Aster de Nouvelle-Angleterre,
Aster des tourbières,
Aster lancéolé,
Aster ponceau,
Barbarée vulgaire,
Benoîte commune,
Benoîte d'Alep,
Benoîte du Canada,
Berle douce,
Berteroa blanc,
Bident feuillu,
Bident penché,
Brasénie de Schreber,
Brunelle commune,
Calla des marais,
Campanule à feuilles rondes,
Campanule fausse-raiponce,
Campanule faux-gaillet,
Carotte sauvage,
Caulophylle géant,
Chardon des champs,
Chardon vulgaire,
Chénopode blanc,
Chèvrefeuille du Canada,
Chicorée sauvage,
Chimaphile à ombelles,
Cicutaire bulbifère,
Circée du Canada,
Claytonie de Caroline,
Clématite de Virginie,
Clintonie boréale,
Coronille bigarée,
Corydale toujours verte,
Cryptoténie du Canada,
Cypripède jaune,
Cypripède rose,
Dentaire à deux feuilles,
Desmodie glutineuse,
Dicentre à capuchon,
Dicentre du Canada,
Dièreville chèvrefeuille,
Égopode podagraire ,
Épervière des prés,
Épervière en ombelle,
Épervière orangée,
Épervière paniculée,
Épiaire à feuilles minces,
Épifage de Virginie,
Épigée rampante,
Épilobe à feuilles étroites,
Épilobe hirsute,
Épipactis petit-hellébore,
Érythrone d'Amérique,
Eupatoire maculée,
Eupatoire perfoliée,
Eupatoire rugueuse,
Euphorbe cyprès,
Euphraise des bois,
Fraisier des bois,
Fraisier des champs,
Gaillet à trois fleurs,
Gaillet mollugine,
Gaillet palustre,
Galane glabre,
Galéopside à tige carrée,
Géranium de Robert,
Gérardie à feuilles ténues,
Germandrée du Canada,
Gesse à feuilles larges,
Gesse aphylle,
Grand nénuphar jaune,
Grande bardane,
Grande molène,
Grande ortie,
Hélianthe à feuilles étalées,
Hémérocalle fauve,
Hépatique à lobes aigus,
Hépatique à lobes ronds,
Hydrophylle de Virginie,
Hydrophylle du Canada,
Immortelle blanche,
Impatiente du Cap,
Impatiente pâle,
Inule aunée,
Iris versicolore,
Julienne des dames,
Laiteron des champs,
Laitue du Canada,
Laportéa du Canada,
Lierre terrestre,
Linaire vulgaire,
Linnée boréale,
Liseron des haies,
Lobélie cardinale,
Lobélie gonflée,
Lotier corniculé,
Luzerne cultivée,
Lycope à une fleur,
Lysimaque ciliée,
Lysimaque terrestre,
Lysimaque thyrsiflore,
Maïanthème du Canada,
Marguerite blanche,
Mauve musquée,
Mauve négligée,
Médéole de Virginie,
Mélampyre linéaire,
Mélilot blanc,
Mélilot jaune,
Menthe des champs,
Millepertuis commun,
Millepertuis de Fraser,
Millepertuis elliptique,
Mimule à fleurs entrouvertes,
Mitrelle à deux feuilles,
Molène blattaire,
Monotrope uniflore,
Morelle douce-amère,
Moutarde des champs,
Myosotis laxiflore,
Myosoton aquatique,
Nymphéa odorant,
Œillet arméria,
Onagre bisannuelle,
Onagre parviflore,
Onagre piloselle,
Orchis grenouille,
Osmorhize de Clayton,
Oursin à têtes rondes,
Oxalide cornue,
Oxalide de Dillenius,
Pain-de-perdrix,
Panais sauvage,
Pédiculaire du Canada,
Penstémon pâle,
Petite herbe à poux,
Phryma à épis grêles,
Pigamon dioïque,
Pigamon pubescent,
Pissenlit officinal,
Plantain majeur,
Platanthère papillon,
Pontédérie cordée,
Populage des marais,
Potentille argentée,
Potentille de Norvège,
Potentille dressée,
Potentille simple,
Pyrole elliptique,
Quatre-temps,
Quenouille à feuilles étroites,
Quenouille à feuilles larges,
Renoncule à bec recourbé,
Renoncule abortive,
Renoncule âcre,
Renoncule rampante,
Renouée à noeuds ciliés,
Renouée de Pennsylvanie,
Renouée sagittée,
Rosier aciculaire,
Rubanier à fruits verts,
Rudbeckie hérissée,
Rudbeckie laciniée,
Sagittaire à larges feuilles,
Salicaire commune,
Salsifis des prés,
Salsifis majeur,
Sanguinaire du Canada,
Sanicle du Maryland,
Saponaire officinale,
Sarriette acinos,
Sarriette vulgaire,
Saxifrage de Virginie,
Sceau-de-Salomon à deux fleurs,
Sceau-de-Salomon pubescent,
Scrofulaire du Maryland,
Scutellaire toque,
Silène blanc,
Silène enflé,
Silène noctiflore,
Smilacine à grappes,
Spiranthe penchée,
Spirée blanche,
Spirée tormenteuse,
Streptope à feuilles embrassantes,
Streptope rose,
Tanaisie vulgaire,
Thé des bois,
Tiarelle cordifoliée,
Trèfle blanc,
Trèfle doré,
Trèfle rouge,
Trientale boréale,
Trille blanc,
Trille ondulé,
Trille rouge,
Trioste perfolié,
Tussilage pas d'âne,
Utriculaire vulgaire,
Uvulaire à grandes fleurs,
Uvulaire perfoliée,
Valériane officinale,
Verge d'or à feuilles de graminée,
Verge d'or à tige zigzagante,
Verge d'or bleuâtre,
Verge d'or du Canada,
Verge d'or rugueuse,
Verge d'or squarreuse,
Vergerette de Philadelphie,
Vergerette rude,
Véronique officinale,
Verveine hastée,
Vesce jargeau,
Violette du Canada,
Violette du Labrador,
Violette parente,
Violette pubescente,
Violette réniforme,
Viorne bois d'orignal,
Vipérine commune
`.split(',').map(item => item.trim()),
    familyname: `
Adoxacées,Alismatacées,Alliacées,Amaranthacées,Apiacées,Apocynacées,Aracées,Araliacées,Aristolochiacées,Astéracées,
Balsaminacées,Berbéridacées,Boraginacées,Brassicacées,
Cabombacées,Campanulacées,Caprifoliacées,Caryophyllacées,Colchicacées,Convolvulacées,Cornacées,
Éricacées,Euphorbiacées,Fabacées,Géraniacées,Hémérocallidacées,Hydrophyllacées,Hypéricacées,
Iridacées,Lamiacées,Lentibulariacées,Liliacées,Lythracées,Malvacées,Mélanthiacées,Montiacées,
Nymphéacées,Onagracées,Orchidacées,Orobanchacées,Oxalidacées,
Papavéracées,Phrymacées,Plantaginacées,Polygonacées,Pontédériacées,Primulacées,
Renonculacées,Rosacées,Rubiacées,Ruscacées,Saxifragacées,Scrofulariacées,Solanacées,
Typhacées,Urticacées,Verbénacées,Violacées`.split(',').map(item => item.trim()),
    abouttitle: "À propos",
    /*abouttext: [
      "Qu'aimeriez-vous savoir sur le Projet de fleurs sauvages de Gatineau?",
      "Où est la Gatineau?",
      "Qu'est-ce qu'une fleur sauvage?"
    ],*/
    aboutprojecttitle: "Le projet,Le projet".split(','),
    querytitle: "Recherche de fleurs",
    queryresults: "résultats",
    queryfiltername: "Couleur des fleurs,Forme des feuilles,Disposition des feuilles,Mois de floraison,Espèce,Nom,Famille,Numéro du sentier".split(","),
    querydone: "FINI",
    yes: "oui",
    no: "non",
    flowerdetailslabels: 'Nom,Famille,Indigène,Couleur des fleurs,Forme des feuilles,Disposition des feuilles,Mois de floraison,Nombre de photos'.split(',')
  }

  // Spanish
  const es = {
    gwp: "Proyecto de flores silvestres de Gatineau",
    welcome: "Buenos Dias",
    all: "TODOS",
    colour: "blanco,amarillo,rojo,violeta,verde,marrón,naranja,azul,rosa".split(','),
    leaf: "simple,compound,none".split(','),
    arrangement: "alternate,basal,whorled,opposite,none".split(','),
    floweringin: 'Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre'.split(','),
    familyname: null
  }

  // German
  const de = {
    gwp: "Gatineau Wildblumenprojekt",
    welcome: "Guten Tag",
    all: "ALLES",
    colour: "weiß,gelb,rot,lila,grün,braun,orange,blau,pink".split(','),
    leaf: "simple,compound,none".split(','),
    arrangement: "alternate,basal,whorled,opposite,none".split(','),
    floweringin: 'Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember'.split(','),
    familyname: null
  }

  // Latin
  const la = {
    gwp: "Gatineau flos feram Project",
    welcome: "Salve",
    all: "OMNIS",
    colour: "album,luteus,rubrum,purpura,viridis,brunneis,aureus,caeruleo,rosea".split(','),
    leaf: "simple,compound,none".split(','),
    arrangement: "alternate,basal,whorled,opposite,none".split(','),
    floweringin: 'Ianuarius,Februarius,Martius,Aprilis,Maius,Iunius,Iulius,Augustus,September,October,November,December'.split(','),
    familyname: null,
    abouttitle: "About",
    abouttext: [
    "Vis scire quid futurum de Gatineau Wildflower Project?",
       "Gatineau Ubi est?",
       "Quod est flos feri!",
       "Quid est, conatur et implerem project?"
    ]
  }

  // Russian
  const ru = {
    gwp: "Проект Полевой цветок Гатино",
    welcome: "Здравствуйте",
    homebutton: "Запрос, О нас, Контакт, Ссылки, Авторские права".split(','),
    all: "ВСЕ",
    screen: "Главная, Запрос, Цветы, Детали Цветка, О нас, Контакт, Ссылки, Авторские права".split(','),
    colour: "белый,желтый,красный,фиолетовый,зеленый,коричневый,оранжевый,синий,розовый".split(','),
    leaf: "simple,compound,none".split(','),
    arrangement: "alternate,basal,whorled,opposite,none".split(','),
    floweringin: 'январь,февраль,март,апрель,май,июнь,июль,август,сентябрь,октябрь,ноябрь,декабрь'.split(','),
    familyname: null,
    abouttitle: "насчет",
    abouttext: [
    "Что бы вы хотели знать о проекте Gatineau Wildflower?",
       "Где Гатино?",
       "Что такое полевой цветок?",
       "Чего пытается достичь проект?"
    ]
  }

  const strings = {
    en_CA,
    fr_CA,
    en: en_CA,
    fr: fr_CA,
    es,
    de,
    la,
    ru
  }

  //console.log(JSON.stringify(strings, null, 2));
  //console.log(en_CA.trail);

  if (locale == "All") {return strings}
  if (collection == "All") {return strings[locale]}
  return strings[locale][collection];
}
